config/routes.rb
Rails.application.routes.draw do


 resources :cashes
 


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cash.rb
class Cash < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cashes_controller.rb
class CashesController < ApplicationController
  def index
    @cashes = Cash.all
  end

  def new
    @cash = Cash.new
  end

  def create
    @cash = Cash.new(cash_params)

    if @cash.save
      redirect_to cashes_path, notice: 'Criado com sucesso'
    else
      render action: :new
    end
  end

  def edit
    
  end

  def update

    if @cash.update_attributes(cash_params)
      
      redirect_to cashes_path, notice: 'Atualizado com sucesso'
      else
        render action: :edit      
    end    
  end

  def show
  end

  def destroy
    @cash.destroy

    redirect_to cashes_path, notice: 'Removido com sucesso'
end

before_action :load_cash, except: [:index,:new, :create]
def load_cash
  @cash = Cash.find(params[:id])
end
 

def cash_params
  params
  .require(:cash)
     .permit(
      :requests,
      :deliveries,
      :input,
      :exits,
      :profit
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cashes_helper.rb
module CashesHelper
end

app/views/cashes/_cash.html.erb
    <tr>
    <td><%= cash.requests %></td>
    <td><%= cash.deliveries %></td>
    <td><%= cash.input %></td>
    <td><%= cash.exits %></td>
    <td><%= cash.profit = (cash.input.to_d - cash.exits.to_d) %></td>
    <td>
    <%= link_to "Mostrar",cash_path(cash)%>
    <%= link_to "Editar",edit_cash_path(cash)%>
    <%= link_to "Remover",cash_path(cash), method: :delete, data:{confirm:'Deseja remover?'}%>
    </td>
    </tr>

app/views/cashes/_form.html.erb
  <%= simple_form_for  @cash do |f| %> 


    <p><strong>
      
    <%= f.input :requests, as: :numeric%>
      
    </p></strong>

    <p><strong>
        <%= f.input :deliveries, as: :numeric%>
      </strong>
    </p>

    <p><strong>
      <%= f.input :input, as: :numeric%>
    </p></strong>

      <p><strong>
        <%= f.input :exits, as: :numeric%>
    </p></strong>


  <%= link_to 'Voltar', cashes_path %>
    
    <p><br>
      <%= f.submit 'Salvar'%>
    </p></br>
  <% end -%>

app/views/cashes/_no_record.html.erb
<tr>
<td colspan='5'>Fluxo de Caixa2</td>
</tr>

app/views/cashes/create.html.erb
<h1>Cashes#create</h1>
<p>Find me in app/views/cashes/create.html.erb</p>

app/views/cashes/destroy.html.erb
<h1>Cashes#destroy</h1>
<p>Find me in app/views/cashes/destroy.html.erb</p>

app/views/cashes/edit.html.erb
<h1>Editar </h1>

<%= render partial: 'form' %>


    

app/views/cashes/index.html.erb
    <h2>Fluxo de Caixa</h2>

    <br><br>
    <%= link_to "Novo Cadastro", new_cash_path %>
    </br></br>


    <table>
    <thead>

    <tr>
    <th><%=Cash.human_attribute_name(:requests) %></th>
    <th><%=Cash.human_attribute_name(:deliveries) %></th>
    <th><%=Cash.human_attribute_name(:input) %></th>
    <th><%=Cash.human_attribute_name(:exits) %></th>
    <th><%=Cash.human_attribute_name(:profit) %></th>
    <th>&nbsp;</th>
    </tr>
    </thead>
    <tbody>
    <%= render(partial: "cash", collection: @cashes ) || render(partial: "no_record")%>
    </tbody>
    </table>

app/views/cashes/new.html.erb
    <h1>Novo</h1>

    <%= render partial: 'form' %>

app/views/cashes/show.html.erb
    <h1>Fluxo de Caixa</h1>

    <p id="notice"><%= notice %></p>
    <p>
    <strong><%= Cash.human_attribute_name(:Pedido)%>:
    </strong><%= @cash.requests %>
    </p>

    <p>
    <strong><%= Cash.human_attribute_name(:Entrega)%>:
    </strong><%= @cash.deliveries %>
    </p>

    <p>
    <strong><%= Cash.human_attribute_name(:Entrada)%>:
    </strong><%= @cash.input %>
    </p>

    <p>
    <strong><%= Cash.human_attribute_name(:Saída)%>:
    </strong><%= @cash.exits %>
    </p>

    <%= link_to 'Voltar', cashes_path %>

app/views/cashes/update.html.erb
<h1>Cashes#update</h1>
<p>Find me in app/views/cashes/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CashFlow</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  
    <%= yield %>


  </body>
</html>